name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abrarkhan916/dashboard-project
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
